### ISSUE TITLE
payload is not executed

### ISSUE THREAD

**Issue by YuriMaram** [0xC01DF00D/Collabfiltrator#3]
Congratulations on the tool and the proposal, I'm testing it locally, but I don't get the command output, see below an example:
Server:		127.0.0.1
Address:	127.0.0.1#53
Non-authoritative answer:
Name:	0000.cm9vdAo-E-F.etb73ubqliyg0b7zyurzqrju1l7dv2.burpcollaborator.net
Address: 52.16.21.24
** server can't find 0000.cm9vdAo-E-F.etb73ubqliyg0b7zyurzqrju1l7dv2.burpcollaborator.net: NXDOMAIN

**Comment by 0xC01DF00D** [comment]
It looks like your DNS lookup stopped short of forwarding to an authoritative server that would have those records, such as google's 8.8.8.8. 

I'm considering adding a config section to the tool to allow users to force the lookup server to 8.8.8.8 in order to bypass this, however, this makes the generated payload longer and in some cases, payload length is important.

If you add:
`nameserver 8.8.8.8`
to /etc/resolv.conf, it should enable it to work locally if you're curious to see how it works.
